config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  get "about" => "pages#about"

  devise_for :users

  resources :users, only: [:show]
  resources :events
  resources :categories
  resources :profiles, only: [:new, :edit, :create, :update]
  resources :photos
  resources :events do
    resources :registrations, only: [:create]
  end

  namespace :api do
    resources :events
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: true
  has_and_belongs_to_many :categories
  has_many :photos, dependent: :destroy
  has_many :registrations, dependent: :destroy
  has_many :guests, through: :bookings, source: :user

  validates :name, presence: true
  validates :description, presence: true, length: {maximum: 500}
  validates :location, presence: true
  validates :starts_at, presence: false
  validates :capacity, presence: false
  validates :price, presence: true

  def bargain?
     price < 30
  end

  def self.alphabetical
    order(name: :asc)
  end


  scope :published, -> {where(active: true)}

  def self.during(start_date, end_date)
      where('starts_at < ? and ends_at > ?', start_date, end_date)
  end

  scope :starts_on_date, -> (start_date) {where(starts_at: start_date)}

  scope :ends_on_date, -> (end_date) {where(ends_at: end_date)}

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.by_initial(letter)
    where("first_name LIKE ?", "#{letter}%").order(:first_name)
  end
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event

  def set_total_price
    self.price = event.price
    total_days = (ends_at.to_date - starts_at.to_date).to_i
    self.total = price * total_days
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_token

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events, dependent: :destroy
  has_one :profile
  has_many :registered_events, through: :registrations, source: :event

  def has_profile?
    profile.present? && !profile.id.nil?
  end

  def full_name
    profile.full_name
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

before_action :set_event, only: [:show, :edit, :update]
before_action :authenticate_user!, except: [:show]

  #fetching all events for current user
  def show
    @categories = @event.categories
    @photos = @event.photos
  end


  def index
      @events = current_user.events
    end



    #building new event for current user using build method
    def new
      @event = current_user.events.build
    end

    def create
      @event = current_user.events.build(event_params)

      if @event.save
        image_params_each do |image|
          @event.photos.create(image: image)
        end

        redirect_to edit_event_path(@event), notice: "Event successfully created"
      else
        render :new
      end
    end


    def update
      if @event.update(event_params)
        redirect_to @event, notice: "Event successfully updated"
      else
        render :edit
      end
    end

    def edit
      if current_user.id == @event.user.id
        @photos = @event.photos
      else
        redirect_to root_path, notice: "You don't have permission."
      end
    end

    private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :description, :location, :includes_food, :includes_drinks, :price, :starts_at, :ends_at, :capacity, :active, category_ids: [])
    end

    def image_params
      params[:images].present? ? params.require(:images) : []
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @event = photo.event
    if @event.user.id == current_user.id
      photo.destroy

      redirect_to edit_room_path(@event), notice: "Photo sucessfully removed"
    else
      redirect_to @event, notice: "Cannot delete that photo"
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :bio)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
   @user = User.find(params[:id])
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
      <div class="container">
        <h1> Welcome to Bamboo Quacking! </h1>
        <p>What is Bamboo Quacking, you might ask? It's the coolest, newest place to create events and meet people who are bamboo-quacking-minded :) </p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; 2016 Company, Inc.</p>
      </footer>
    </div> <!-- /container -->

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurup", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

      <li><%= link_to "About", about_path %></li>


        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>

        <% else %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.has_profile? ? current_user.full_name : current_user.email  %> <span class="caret"></span></a>

          <ul class="dropdown-menu">
            <li><%= link_to "Your Events", events_path %></li>
            <li role="separator" class="divider"></li>

            <% if current_user.has_profile? %>
              <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
            <% else %>
              <li><%= link_to "Create Profile", new_profile_path %></li>
            <% end %>
            <li><%= link_to "Edit Password", edit_user_registration_path %></li>

            <li role="separator" class="divider"></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>