config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  get "about" => "pages#about"

  devise_for :users

  resources :users, only: [:show]
  resources :events
  resources :categories
  resources :profiles, only: [:new, :edit, :create, :update]
  resources :photos
  resources :events do
    resources :registrations, only: [:create]
  end

  namespace :api do
    resources :events
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: true
  has_and_belongs_to_many :categories
  has_many :photos, dependent: :destroy
  has_many :registrations, dependent: :destroy
  has_many :guests, through: :bookings, source: :user

  validates :name, presence: true
  validates :description, presence: true, length: {maximum: 500}
  validates :location, presence: true
  validates :starts_at, presence: false
  validates :capacity, presence: false
  validates :price, presence: true

  def bargain?
     price < 30
  end

  def self.alphabetical
    order(name: :asc)
  end


  scope :published, -> {where(active: true)}

  def self.during(start_date, end_date)
      where('starts_at < ? and ends_at > ?', start_date, end_date)
  end

  scope :starts_on_date, -> (start_date) {where(starts_at: start_date)}

  scope :ends_on_date, -> (end_date) {where(ends_at: end_date)}

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.by_initial(letter)
    where("first_name LIKE ?", "#{letter}%").order(:first_name)
  end
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event

  def set_total_price
    self.price = event.price
    total_days = (ends_at.to_date - starts_at.to_date).to_i
    self.total = price * total_days
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_token

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events, dependent: :destroy
  has_one :profile
  has_many :registered_events, through: :registrations, source: :event

  def has_profile?
    profile.present? && !profile.id.nil?
  end

  def full_name
    profile.full_name
  end
end

app/controllers/api/events_controller.rb
class Api::EventsController < ApplicationController

  def index
    events = Event.all
    render status: 200, json: events
  end


  def show
    event = Event.find(params[:id])
    render status: 200, json: event
  end

  def create
    event = Event.new(event_params)

    if event.save
      render status: 201, json: event
    else
      render status: 422, json: {
        errors: event.errors
      }.to_json
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy

    render status: 200, json: {
      message: "Event successfully deleted"
    }.to_json
  end

  def update
    event = Event.find(params[:id])

    if event.update(event_params)
      render status: 200, json: events
    else
      render status: 422, json: {
        message: "the event could not be updated",
        errors: event.errors
      }.to_json
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :location, :includes_food, :includes_drinks, :price, :starts_at, :ends_at, :capacity, :active )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

before_action :set_event, only: [:show, :edit, :update]
before_action :authenticate_user!, except: [:show]

  #fetching all events for current user
  def show
    @categories = @event.categories
    @photos = @event.photos
  end


  def index
      @events = current_user.events
    end



    #building new event for current user using build method
    def new
      @event = current_user.events.build
    end

    def create
      @event = current_user.events.build(event_params)

      if @event.save
        image_params_each do |image|
          @event.photos.create(image: image)
        end

        redirect_to edit_event_path(@event), notice: "Event successfully created"
      else
        render :new
      end
    end


    def update
      if @event.update(event_params)
        redirect_to @event, notice: "Event successfully updated"
      else
        render :edit
      end
    end

    def edit
      if current_user.id == @event.user.id
        @photos = @event.photos
      else
        redirect_to root_path, notice: "You don't have permission."
      end
    end

    private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :description, :location, :includes_food, :includes_drinks, :price, :starts_at, :ends_at, :capacity, :active, category_ids: [])
    end

    def image_params
      params[:images].present? ? params.require(:images) : []
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @event = photo.event
    if @event.user.id == current_user.id
      photo.destroy

      redirect_to edit_room_path(@event), notice: "Photo sucessfully removed"
    else
      redirect_to @event, notice: "Cannot delete that photo"
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :bio)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
before_action :authenticate_user!

  def create
    @registrations = current_user.registrations.create(registration_params.merge(room_id: params[:room_id]))
    @registration.set_to_total_price
    @registration.save

    redirect_to_@registration.event, notice: "Thank you for registering!"
  end

  private

  def registration_params
    params.require(:registration).permit(:starts_at, :ends_at)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
   @user = User.find(params[:id])
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true } do |f| %>


  <div class="form-group">
    <label>Event Name</label>
    <%= f.text_field :name, placeholder: "Event name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Description</label>
    <%= f.text_area :description, rows: 5, placeholder: "Say something about your event", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Location</label>
    <%= f.text_field :location, placeholder: "Location", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Capacity</label>
    <%= f.text_field :capacity, placeholder: "Capacity", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Start Time</label>
    <%= f.text_field :starts_at, placeholder: "Ex. 2017-03-19 18:00", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>End Time</label>
    <%= f.text_field :ends_at, placeholder: "Ex. 2017-03-19 23:00", class: "form-control" %>
  </div>

  <label>Other Event Details</label>

  <div class="form-group">
    <%= f.check_box :includes_food %> Will have food
  </div>
  <div class="form-group">
    <%= f.check_box :includes_drinks %> Will have drinks
  </div>

  <div class="form-group">
    <label>Price</label>
    <div class="input-group">
      <div class="input-group-addon">€</div>
      <%= f.number_field :price, placeholder: "eg. 20", class: "form-control" %>
    </div>
  </div>

  <label>Photos</label>
  <div class="form-group">
    <span class="btn btn-default">
      Upload photos
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </span>
  </div>

  <div id="photos">
  <%= render 'photos/list' %>
  </div>

  <label>Publish this event?</label>

  <div class="form-group">
    <%= f.check_box :active %> Active
  </div>

  <label>Categories</label>

<%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
  <div class="form-group">
    <%= b.check_box(class: "check_box") %> <%= b.object.name %>
  </div>
<% end %>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit place
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Events", events_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", events_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your Events
      </div>
      <div class="panel-body">

        <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-7">
            <h4><%= event.name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "View", event, class: "btn btn-default" %>
            <%= link_to "Update", edit_event_path(event), class: "btn btn-default" %>
          </div>
        </div>
        <% end %>

      </div>
    </div>

    <%= link_to "Add new event", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<% if current_user != @event.user %>
  <div class="panel panel-primary">
    <div class="panel-heading">Register for this event</div>

    <div class="panel-body">
      <% render 'registrations/form' %>
    </div>
  </div>
<% end %>


<div class="panel panel-primary">
  <div class="panel-heading"><h1><%= @event.name %></h1></div>

  <div class="panel-body">

    <p>Address: <%= @event.location %></p>
    <p>Host: <%= @event.user.email %></p>



    <!-- About -->
    <h4>About</h4>
    <p><%= @event.description %></p>


    <h4>Event Details</h4>
    <ul class="amenities">
      <li> Price: <%= @event.price %></li>
      <li><%= !@event.includes_food ? ("<s>Food</s>").html_safe : "Food" %></li>
      <li><%= !@event.includes_drinks ? ("<del>Drinks</del>").html_safe : "Drinks" %></li>
      <li> Capacity: <%= @event.capacity %></li>
      <li> Start Time: <%= @event.starts_at %></li>
      <li> Ending Time: <%= @event.ends_at %></li>

    </ul>

    <h4>Categories</h4>
    <% @categories.each do |category| %>
  <span class="label label-success"><%= category.name %></span>
    <% end %>

    <h4>Photos</h4>
  <% @event.photos.each do |photo| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= image_tag photo.image.thumbnail %>
    </div>
  </div>
  <% end %>
  </div>

</div>

<%= link_to "Back", events_path, class: "btn btn-default" %>